# This file specifies the contents of './forge_modules'
#
# Run 'rake forge' to have librarian-puppet update that folder.

forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs/apt'
mod 'puppetlabs/java'
mod 'puppetlabs/stdlib'
mod 'puppetlabs/vcsrepo'
mod 'maestrodev/wget'
